### ISSUE TITLE
the ERP Core dataset has an invalid `participants.tsv`

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#16]
this is related to #5; the `participants.tsv` contains sub-004, but there is no EEG data for sub-004

@CPernet will fix this in the analysis script

**Comment by CPernet** [comment]
fixing via code here https://github.com/SIESTA-eu/wp15/blob/main/usecase-2.4/ERP_Core_WB.m#L99
not specific to sub-004, instead matches what in the table with what is on drive, resave table then use the BIDS import.
