### ISSUE TITLE
BIDSScramble suggestions

### ISSUE THREAD

**Issue by arnodelorme** [SIESTA-eu/wp15#19]
- BIDS scrambler: Took me a while (5 minutes :-) to understand what it did and why it was there. It is a good name. I think this step could be skipped for naive users as it makes everything more complex (they will not understand why, and for them it is meaningless). Maybe have a pipeline with and without it? Or maybe it could be introduced at a later stage in a tutorial?

- I feel that there should be a compiled executable for Windows of BIDSscrambler that can be used on regular dos prompts because the install of Python can be complex on Windows (needs its own customized dos prompt as path are not added by default to the regular dos prompt etc.).

- The commands provided in the tutorial should be Unix and Dos compatible (or a version of each). There should be additional instructions for paths (most people will not have the matlab or R commands in their path as they usually click the icons).

- For Mac, the BIDSscrambler should run on the default python install of OSx (not require virtualenv or Conda — these are steps that naive users can take days to master and understand — if they ever do). Yes, it is not ideal and recommended, but will be fine for most users who are occasional Python users. Even though I use Conda myself, I always use the same Python environment where I know I have 100+ librairies installed. Only issue is that the default osx Python is very old (v3.7 for me), but I think this is an acceptable limitation for something as simple as BIDSscrambler (plus advanced users will use Conda or Virtualenv).

**Comment by robertoostenveld** [comment]
Regarding your point 1: at this moment we don't have SIESTA platform "users" yet, those are only conceived to come into the picture after month 18 in the SIESTA project when the actual implementation starts. So right now we have "developers" that should partially act as if they were the users - to identify usability requirements. 

The neuroscientists that work on wp15 therefore have to act both as future "users" but also as "developers" (since the platform does not build itself). Wp15 is about developing use cases. The use cases should be in line of those of future (more naive) users.

**Comment by robertoostenveld** [comment]
Regarding your point 2: AFAIK the SIESTA cloud platform only targets linux. But it would be a nice stretch goal to implement BIDScramble such that it also works on macOS and Windows, so that BIDScramble can also be used outside the SIESTA platform.

**Comment by marcelzwiers** [comment]
>     * I feel that there should be a compiled executable for Windows of BIDSscrambler that can be used on regular dos prompts because the install of Python can be complex on Windows (needs its own customized dos prompt as path are not added by default to the regular dos prompt etc.).

Sorry, but that is simply not true. Users can just go to the windows store and install Python (the same as any other app). Then it all runs out of the box, no path setting needed:
https://learn.microsoft.com/en-us/windows/python/beginners
https://docs.python.org/3/using/windows.html#windows-store

>     * For Mac, the BIDSscrambler should run on the default python install of OSx (not require virtualenv or Conda — these are steps that naive users can take days to master and understand — if they ever do). Yes, it is not ideal and recommended, but will be fine for most users who are occasional Python users.

I think teaching users bad practices to make things "easy" is not fine and will cause problems/pain later on. 

> Even though I use Conda myself, I always use the same Python environment where I know I have 100+ librairies installed. Only issue is that the default osx Python is very old (v3.7 for me), but I think this is an acceptable limitation for something as simple as BIDSscrambler (plus advanced users will use Conda or Virtualenv).

It's ok to have a bulk environment to do stuff that you want to do just once or so. But for reproducible science or for software that should be maintained / work in the long run you should isolate your python environment. And it's just one simple command to create an environment and one to activate it.
