### ISSUE TITLE
Improve documentation of use cases overview

### ISSUE THREAD

**Issue by CPernet** [SIESTA-eu/wp15#21]
@arnodelorme suggested something by email we could use for the general readme ...
for each use case, indicate that Linux is the analysis platform expected + 

Modality: 
Processing software used: 
Python knowledge required from 0 to 10: 
MATLAB knowledge  required from 0 to 10: 
R knowledge  required from 0 to 10: 

could be useful?

**Comment by robertoostenveld** [comment]
I have added a table to the top-level `README.md`. Looking at it, I would say that we are MATLAB heavy. It would be good to include an FSL, AFNI, FreeSurfer, or Nipype analysis or so.
