### ISSUE TITLE
Adopt gitignore/bidsignore pattern format for whitelisting

### ISSUE THREAD

**Issue by marcelzwiers** [SIESTA-eu/wp15#23]
Git and BIDS both use the [gitignore](https://git-scm.com/docs/gitignore) pattern format as an effective means to blacklist specific files or directories. We could use the same pattern format to whitelist specific files. For instance, this list:

```
output/group/cluster_cmb_faces_vs_scrambled.html
output/group/cluster_cmb_faces_vs_scrambled.mat
output/group/cluster_cmb_famous_vs_unfamiliar.mat
output/group/diff_cmb_faces_vs_scrambled_cluster.png
output/group/diff_cmb_faces_vs_scrambled.mat
output/group/diff_cmb_faces_vs_scrambled_stat.png
output/group/diff_cmb_famous_vs_unfamiliar.mat
output/group/diff_cmb_famous_vs_unfamiliar.png
output/group/diff_cmb_famous_vs_unfamiliar_stat.png
output/group/neighbours_cmb_distance.png
output/group/neighbours_cmb_triangulation.png
output/group/stat_cmb_faces_vs_scrambled.mat
output/group/stat_cmb_faces_vs_scrambled.png
output/group/stat_cmb_famous_vs_unfamiliar.mat
output/group/timelock_faces_cmb.mat
output/group/timelock_famous_cmb.mat
output/group/timelock_scrambled_cmb.mat
output/group/timelock_unfamiliar_cmb.mat
```

Would become something like:
```
output/group/*scrambled.*
output/group/diff_cmb_famous_vs_unfamiliar*
output/group/neighbours_cmb_*.png
output/group/stat_cmb_faces_vs_scrambled.mat
output/group/stat_cmb_faces_vs_scrambled.png
output/group/stat_cmb_famous_vs_unfamiliar.mat
[etc]
```

**Comment by marcelzwiers** [comment]
It could be easily implemented using e.g. https://github.com/mherrmann/gitignore_parser

**Comment by robertoostenveld** [comment]
FYI, in one of the recent commits I have updated all 4 `whitelist.txt` files so that they are relative to the output directory. The output directory itself is not part of the listed filenames any more.

**Comment by robertoostenveld** [comment]
I think that for now it is better to have a very explicit format for the whitelist, as it will determine which files are to be disclosed/released. We do not accidentally want to share all files in case a wildcard `*` is specified incorrectly.
