### ISSUE TITLE
Implement a subject selection tool for BIDS datasets

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#25]
I would like to have a BIDS application like "BIDSselect " that allows me to do 

```
BIDSselect --keep 1 inputdir outputdir
```

which copies the dataset, but only keeping the first participants data. And similarly, 

```
BIDSselect --remove 1 inputdir outputdir
```

which keeps all participants minus the first one. 

Furthermore, I want this tool to have an option to replace the subject identifiers (in the participants.tsv and in the file names) with new pseudonyms. 

```
BIDSselect --psedonimize inputdir outputdir
```

@marcelzwiers I am not sure whether these two (or three) requests could be integrated in the BIDScramble application. At least there is a lot in common with that application, so code sharing seems important.

**Comment by robertoostenveld** [comment]
Regarding the "scramble" application, I can imagine that it would also have options for selecting subsets of participants, and that it would also have an option of replacing existing subject identifiers with new ones. So if "scramble" would get subcommands for simply copying (not changing) content plus the new features, then I believe that would do the job.

**Comment by marcelzwiers** [comment]
> Regarding the "scramble" application, I can imagine that it would also have options for selecting subsets of participants, and that it would also have an option of replacing existing subject identifiers with new ones. So if "scramble" would get subcommands for simply copying (not changing) content plus the new features, then I believe that would do the job.

I'll look into it, `scramble` already has the `swap` action (which swaps the content of files between subjects, while keeping the filenames as they are), so I expect this can be integrated right there

```console
usage: scramble bidsfolder outputfolder swap [-h] [-s PATTERN] [-d] [-g ENTITY [ENTITY ...]]

Randomly swaps the content of data files between a group of similar files in the BIDS input directory and save
them as output.

options:
  -h, --help            show this help message and exit
  -s PATTERN, --select PATTERN
                        A fullmatch regular expression pattern that is matched against the relative path of the
                        input data. Files that match are scrambled and saved in outputfolder (default: .*)
  -d, --dryrun          Do not save anything, only print the output filenames in the terminal (default: False)
  -g ENTITY [ENTITY ...], --grouping ENTITY [ENTITY ...]
                        A list of (full-name) BIDS entities that make up a group between which file contents are
                        swapped. See: https://bids-
                        specification.readthedocs.io/en/stable/appendices/entities.html (default: ['subject'])

examples:
  scramble data/bids data/pseudobids swap
  scramble data/bids data/pseudobids swap -s '.*\.(nii|json|tsv)'
  scramble data/bids data/pseudobids swap -s '.*(?<!derivatives)'
  scramble data/bids data/pseudobids swap -g subject session run
```

**Comment by marcelzwiers** [comment]
> Furthermore, I want this tool to have an option to replace the subject identifiers (in the participants.tsv and in the file names) with new pseudonyms.

It's a little more complicated than that, subject identifiers also exist in other places, such as in the json sidecars (`IntendedFor` for example), and inside the `sub-*_scans.tsv` files. Also, the BIDS folder may contain extra (bidsignored) data that we don't know how it looks like

**Comment by robertoostenveld** [comment]
> Also, the BIDS folder may contain extra (bidsignored) data that we don't know how it looks like

Both the `scramble` and the `select` functionality should only work on data that we do know. Files in the gitignore should also be ignored by us and not copied, i.e., the data user would never have access to those.

**Comment by marcelzwiers** [comment]
FYI, so far, I've made `scramble` as generic as possible, such that BIDS is always supported, but many other formats are also supported. The way this works is that `scramble` loops over the data in a file-based way, except for the `swap` action, which loops over the layout created by pybids. The pybids layout is currently generated with a hardcoded `validate=False`, but I will make this an optional input flag.
