### ISSUE TITLE
BIDScramble installation fails

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#27]
I created a virtual environment and according to instructions did 
```
git clone https://github.com/SIESTA-eu/wp15.git     # Or download the code yourself
pip install wp15/BIDScramble                        # Or use an alternative installer
```
but get the error
```
Directory 'wp15/BIDScramble' is not installable. File 'setup.py' not found.
```

I believe that in the past it worked ...

**Comment by marcelzwiers** [comment]
That should still work. Which python version is that?

**Comment by marcelzwiers** [comment]
If you use conda you probably need to do something like:
```console
conda create -n bidscramble_test python=3.12
```

**Comment by robertoostenveld** [comment]
I am not using conda but venv, but it might indeed be due to me using a too old (default installed) python version. I will check!

**Comment by marcelzwiers** [comment]
The instruction mention python should be 3.8+

**Comment by marcelzwiers** [comment]
This may be helpful

https://mac.install.guide/python/update

**Comment by robertoostenveld** [comment]
It was my error. I did `module load python` on mentat001, but that results in the default python 3.4 version. I now started with a more recent python version that I got from `module load anaconda3`.

**Comment by robertoostenveld** [comment]
> This may be helpful
> https://mac.install.guide/python/update

Note that this was not on my mac, but on the Donders compute cluster.
