### ISSUE TITLE
Create a bidscrambler for EEG data in the BrainVision Core format

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#28]
The [BrainVision Core file format](https://www.brainproducts.com/support-resources/brainvision-core-data-format-1-0/) is one of the file formats for EEG data supported in BIDS. Compared to the EEGLAB file format (which is also supported), it is much simpler to read and write. Hence I propose that we first implement a scrambler for this format. 

One EEG recording consists of an ascii `.vhdr` (header) and `.vmrk` (marker/events/trigger) file, plus a data file with the actual EEG data. The data file often has the extension `.eeg`, but that extension is not required. The data file name (including extension) is specified _inside_ the header file. 

Both header and marker file resemble the windows-ini and the [TOML](https://toml.io/en/) file format. 

In principle the data file can be either ASCII or binary, and either serialized or multiplexed (and all those files exist in the wild), but the formal 1.0 specification PDF prescribes that it must be multiplexed binary (which makes things much simpler).

**Comment by schoffelen** [comment]
To remind myself: MNE python relies on https://github.com/bids-standard/pybv for their (somewhat limited, i.e. it does not support a round trip in reading and writing) Brainvision IO

**Comment by schoffelen** [comment]
I will have a stab at this one.

**Comment by robertoostenveld** [comment]
Note that this issue was duplicated in #31 and has been implemented with pull request #32
