### ISSUE TITLE
use case 2.2 - morphometric values from MRI for different parts of the brain 

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#3]
[Structural (t1) images of 136 young healthy adults; study of effects of chronotype, sleep quality and daytime sleepiness on brain structure.](https://openneuro.org/datasets/ds003826/versions/3.0.1)

The data set includes a small tabular entry characterising human participants and structural MRI data.

Results to be produced are of the tabular type, computing morphometric values for different parts of the brain and reporting of statistical analyses.

The brain data analysis is fully automated. Statistical analyses ?? 

Relies on matlab/spm and freesurfer (executable) - the dataset includes 146 subjects (1,18GB)

**Comment by marcelzwiers** [comment]
The MRIQC pipeline works on my side and I have created several scrambling filters (the latest one is "swap"). Now it is time to test these filters and see how anonymous the scrambled data is and whether MRIQC can still produce sensible output from it

**Comment by CPernet** [comment]
once we are done with the tabular data -  Emilie and I stated looking at another library from B Thirion's group in Paris allowing to do some measures for data anonymity on brain data as well :-) so we'll help you there as well
