### ISSUE TITLE
Implement scrambling of EEG data for use case 2.4

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#31]
@marcelzwiers @schoffelen @arnodelorme @CPernet 

For your information, I am working on the implementation of the BrainVision Core data format in the BIDScramble. The EEGLAB `.set` format is too complex for now, but the data in use case 2.4 can be converted (using FieldTrip) from EEGLAB to BrainVision format without compromising the analysis pipeline. 

As the [pybv](https://github.com/bids-standard/pybv reader was a bit of a mess with regards to dependencies and not symmetric in reading and writing, I implemented my own BrainVision read and write package. See http://github.com/robertoostenveld/brainvision. I will make sure that this gets added to pypi to allow installation with pip.

**Comment by robertoostenveld** [comment]
The BrainVision code is now on PyPi at https://pypi.org/project/brainvision/. 

I implemented an automatic release "action" following the instructions at https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d

**Comment by schoffelen** [comment]
As discussed with @CPernet we need to come up with a few thought-through meaningful scrambling options for MEEG data, beyond time series scrambling. Let's reopen this issue to bounce ideas back and forth.

We probably need to have 2 or 3 additional ways to break the spatio/temporal/spectral structure in the data.

I am currently thinking about a combination of spatial filtering and blockwise scrambling. For ERP'ish application this probably also would need to take the structure of the events into account.

Specifically, using spatial unmixing (based on 'some' heuristic), then a scrambling step (e.g. scrambling the order of the latent components and/or blockwise scrambling (i.e. keeping the overall spectral structure in the data, and/or time-locked to event stuff), then again a spatial mixing step, would be a flexible framework that allows for a mixture of spatiotemporal scrambling, preserving aspects of the overall structure in the data

**Comment by CPernet** [comment]
I agree that within the ICA framework, one is likely able to mess stuff up different ways (after characterizing the evoked and spectral aspects id IC). I also agree (as discussed on line) that often the pipeline will be something like 'can want to see if the pipeline can detect X', so the feature of interest needs somehow to be present.
 
- one could play with the weight matrix ?? maybe as a way to 'remove' known sensitive attributes (not something I'd do by default, but if a data control right holder indicates an aspect that needs nullifying, this can be a way)
- specific IC could be made noisier adding pink noise or a sin where evoked response is (say found IC with spectral / evoked response, ie increase energy following events anytime from 50 to 1000ms, no need to be specific IMO -then add, it exist tools for simulations I used that can be leveraged for that)
- total randomness, chunk time courses based on autocorrelation size (to keep main spectral, autocorrelation) and exchange within/between IC and remix

not sure all makes sense, but putting some ideas down ...

**Comment by robertoostenveld** [comment]
Hi @schoffelen could you test the implemented scrambling of the BrainVision format EEG data?  Starting from the original dataset of 2.4, you can use https://github.com/SIESTA-eu/wp15/blob/main/usecase-2.4/source/ERP_Core_eeglab2brainvision.m to make a BrainVision formatted version for some of the subjects, and then apply BIDScramble. Following scrambling of the EEG data (with the option `brainvision`, the code for that is in https://github.com/SIESTA-eu/wp15/blob/main/BIDScramble/bidscramble/scramble_brainvision.py), the EEG time series should contain random noise. It seems to work in my hands, so I hope that testing for you will be easy.

**Comment by schoffelen** [comment]
I can confirm that the scrambler for brainvision data works.

The current default is nulling, but when I add the ```permute``` as a method, the data are nicely permuted, confirmed by visualizing the time series of a given channel, and by comparing the histograms of the amplitudes of the scrambled and non-scrambled versions. 

One additional observation I had, is that I need to specify ```cfg.readbids='no'``` in order to load the scrambled data into matlab (using ```ft_preprocessing```). The reason for this seems to be that that scrambling (I did a two step approach with:

```
scramble in out stub 
scramble in out brainvisino permute
```

resulted in a dataset with empty run-specific json files, causing fieldtrip to choke)

**Comment by robertoostenveld** [comment]
Would those be the `eeg.json` files that are empty? I believe that empty run-specific json files are not BIDS compliant, which means that BIDScramble has a bug.

**Comment by robertoostenveld** [comment]
Considering my [previous comment](https://github.com/SIESTA-eu/wp15/issues/31#issuecomment-2528313816): upon rereading the documentation I suspect that scramble should also have been called with the `json` action. The `stub` action creates the empty files, the `json` action allows copying json file content over (with or without modifications).

The use case specific scramble instructions should be updated/completed/reviewed. I'll  make a new issue for that.

**Comment by robertoostenveld** [comment]
Anyway, thanks for checking!

**Comment by marcelzwiers** [comment]
> Would those be the `eeg.json` files that are empty? I believe that empty run-specific json files are not BIDS compliant, which means that BIDScramble has a bug.

Is there any documentation on empty json-files being non-compliant? Because I think there is nothing wrong with that (it's not desirable, but also not wrong))

**Comment by robertoostenveld** [comment]
Yes, as I wrote in [this comment](https://github.com/SIESTA-eu/wp15/issues/31#issuecomment-2536222116) I also think it is a user error. Some of the json files should have been copied over with `--preserve`, as those are needed for processing. 

I am surprised that you write that scrambled data can never be BIDS compliant. Why not? In general - with the proper options - I think that the scrambled data would onl;y have different numbers, not a different structure. If not compliant, I don't think that strict BIDS apps like MRIQC will even work on the scrambled data.
