### ISSUE TITLE
usecase-2.5

### ISSUE THREAD

**Issue by Marque-CerCo** [SIESTA-eu/wp15#37]
Hello,

I've almost finalized the project. Currently, all my Matlab files are in one directory. Is it possible to get this directory via the git command line? I have a question about GitHub. In the output section, should I describe the architecture and structure of the output directory? Can a diagram be made to simplify the explanation? 
Sincerely

**Comment by marcelzwiers** [comment]
Please continue the discussion here:

https://github.com/SIESTA-eu/wp15/pull/36
