### ISSUE TITLE
include the whitelist for use case 2.5

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#39]
please add a text file `whitelist.txt` that lists all files resulting from the usecase-2.5 analysis that are to be released

**Comment by Marque-CerCo** [comment]
@robertoostenveld I update the whitelist. Do I need to make any changes or clarifications?

**Comment by robertoostenveld** [comment]
no, this is fine. What I understand is that there are just these two files in the output directory that are to be published/shared.
