### ISSUE TITLE
use case 2.3 - multimodal dataset

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#4]
[The National Institute of Mental Health (NIMH) Intramural Healthy Volunteer Dataset](https://openneuro.org/datasets/ds004215/versions/1.0.2)

The data set includes a large amount of tabular data characterising human participants, structural MRI, and MEG data.

Results to be produced are of the tabular type, computing xxx on the tabular data, and xxx from the brain imaging data.
XXX

Relies on matlab/FieldTrip - the dataset includes 157 participants (357GB)

**Comment by robertoostenveld** [comment]
Both use case 2.3 and 2.4 are based on MATLAB, and both compute an ERP or ERF. To increase the diversity of the use cases, we could modify 2.3 so thaht it uses MNE python to compute the ERFs instead of FieldTrip.

What do you think @schoffelen ? This would mainly require your input. The pipeline could be made even simpler than the current one, for example only compute the N170 difference ERF over the first run (from 6) and then averaged over participants. No artifact rejection or such, just read+segment+average+grandaverage+difference.

**Comment by schoffelen** [comment]
My suggestion would be to first simplify the pipeline in Matlab to prototype it. Given the challenges in getting 2.4 robustly up and running it may be good to have a FieldTrip-only Matlab use case without the challenging eeglab/limo dependencies.

I think I could pull off a simple MNE-based pipeline as sketched above

**Comment by robertoostenveld** [comment]
@schoffelen, please note that I did another cleanup of the code. Besides making use of participants (allowing for re-pseudonimization and leave-one-out resampling), an important change is that the analysis is now on the MaxFiltered files. 

The bias in the group-level statistics due to the different number of trials in the combined planar averages still needs to be addressed.

**Comment by robertoostenveld** [comment]
The bias has also been addressed in the recent commit. 

The next step is to containerize this pipeline in an apptainer. The https://hub.docker.com/r/mathworks/matlab docker images might provide a good starting point. The license for those is implemented by setting an environment variable that points to the network license manager that is to be contacted.

**Comment by robertoostenveld** [comment]
I have constructed a `pipeline.def` for the apptainer (including MATLAB) and tested it on a local linux computer and added it to the wp15 repo. 

@marcelzwiers could also try to build the actual apptainer (test 1) and can you then try to run it on the shared data on our project directory (test 2)?

**Comment by robertoostenveld** [comment]
@marcelzwiers I managed to execute the container on a SLURM compute node, but there are errors inside the container in the path, the data handling and the analysis scrip. I have to fix those first, so don't bother testing yet.

**Comment by robertoostenveld** [comment]
@marcelzwiers I have updated the container and have been able to execute it on a SLURM compute node with 16GB of RAM.  Can you try whether you can also execute the participant and group level analysis according to documentation?

**Comment by marcelzwiers** [comment]
The first thing I get is:
```
mkdir: cannot create directory '/home/mrphys/marzwi/.MathWorks': Read-only file system
```

**Comment by robertoostenveld** [comment]
What have you specified as the output directory and is it properly mounted in the container with the `--bind` option? Can you do `apptainer shell --bind xxx:xxx pipeline.sif` and check that the input and output directories are available inside the container?

**Comment by marcelzwiers** [comment]
> What have you specified as the output directory and is it properly mounted in the container with the `--bind` option? Can you do `apptainer shell --bind xxx:xxx pipeline.sif` and check that the input and output directories are available inside the container?

The data is certainly there, as you can see if I list the input directory:
```console
$ apptainer exec --no-home --env MLM_LICENSE_FILE=26000@matlab.science.ru.nl pipeline.sif ls -l ../usecase-2.3/input
total 164
-rw-r--r--+  1 nobody nogroup 1901 Jun 10 09:50 CHANGES
-rw-r--r--+  1 nobody nogroup 6060 Jun 10 09:50 README
-rw-r--r--+  1 nobody nogroup 1372 Jun 10 09:50 acq-mprage_T1w.json
-rw-r--r--+  1 nobody nogroup 1102 Jun 10 09:50 dataset_description.json
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 derivatives
-rw-r--r--+  1 nobody nogroup  333 Jun 10 09:50 participants.tsv
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-1_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-2_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-3_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-4_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-5_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-6_FLASH.json
-rw-r--r--+  1 nobody nogroup   82 Jun 10 09:50 run-1_echo-7_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-1_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-2_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-3_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-4_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-5_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-6_FLASH.json
-rw-r--r--+  1 nobody nogroup   83 Jun 10 09:50 run-2_echo-7_FLASH.json
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 stimuli
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-01
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-02
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-03
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-04
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-05
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-06
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-07
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-08
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-09
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-10
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-11
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-12
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-13
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-14
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-15
drwxr-xr-x+  4 nobody nogroup 4096 Jun 10 09:50 sub-16
drwxr-xr-x+ 10 nobody nogroup 4096 Jun 10 09:50 sub-emptyroom
-rw-r--r--+  1 nobody nogroup  718 Jun 10 09:50 task-facerecognition_beh.json
-rw-r--r--+  1 nobody nogroup 1981 Jun 10 09:50 task-facerecognition_bold.json
```

**Comment by marcelzwiers** [comment]
I can also use mkdir normally:
```console
dccn-c062/marzwi$ apptainer exec --no-home pipeline.sif mkdir test
dccn-c062/marzwi$ ls -al
total 2363892
drwxr-xr-x  3 marzwi       4096 Aug 28 11:20 ./
drwxr-xr-x 10 jansch       4096 Aug 27 14:12 ../
drwxr-xr-x  2 marzwi       4096 Aug 28 11:20 test/
-rwxr-xr-x  1 marzwi 2411110400 Aug 27 14:25 pipeline.sif*
```

**Comment by robertoostenveld** [comment]
The way you specify the apptainer commands you are relying on the local directory being mounted and writable from within the container. I think you should more explicitly specify the full path and use --bind to mount them. Something like 

```
apptainer run --bind /project/30xxxx/siesta/usercase-2.3/input:/work/input --bind /project/30xxxx/siesta/usercase-2.3/output:/work/output pipeline.sif /work/input /work/output participant
```

**Comment by marcelzwiers** [comment]
So on mentat001s this now works normally (i.e. with the default DCCN binds):
```console
$ apptainer run --no-home --env MLM_LICENSE_FILE=26000@matlab.science.ru.nl pipeline.sif ../usecase-2.3/input/ output participant
```

**Comment by robertoostenveld** [comment]
The consideration for the input and outputdir to be specified as environment variables into MATLAB was that that would allow for spaces, dashes/minus or other non-ideal symbols to be used in the path name, and that I prefer the top-level analysis to be implemented as a script, not a function (for debugging reasons). When I am back, we should look into why my first implementation failed for you but worked for me. But for now happy that you can execute the pipeline without knowing i detail what it is doing.

**Comment by marcelzwiers** [comment]
The code wasn't catching spaces also in the old code, but I now fixed that. Using input arguments is best practice and now running code inside or outside the container is exactly the same. Debugging can of course be easily done using dbstops or temporarily removing the first line.

**Comment by robertoostenveld** [comment]
this has been resolved
