### ISSUE TITLE
convert fMRI analysis into a BIDS application

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#42]
@Marque-CerCo can you have a look at https://github.com/SIESTA-eu/wp15/tree/main/usecase-2.1/source and specifically how the `pipeline.m` and `bidsapp.m` work together?  I have already copied the `bidsapp.m` into `usecase-2.5/source` but it still needs to be integrated with the `workPackageCerCo.m` function.

Use case 2.1 is the simplest, but 2.3 can also be used as example. Note that (as usual) you should do a `git pull` to get the most recent changes.

As soon as `bidsapp.m` can be called, the container will also work. The only difference that remains in the MATLAB based containers for the different use cases is in the installation of the dependencies, but all of them call the MATLAB bidsapp in the same way.

On the matlab-command line you should be able to do 

```
bidsapp <inputdir> <outputdir> <level>
```

or

```
bidsapp -h
```

without any `()` brackets and quotes, since MATLAB will then automatically pass the options to the function as strings. That is the same as specifying either `save matlab.mat var` or `save('matlab.mat', 'var')`.

**Comment by Marque-CerCo** [comment]
@robertoostenveld I'm just looking at the bidsapp.m file. I'll see how it works with the previous usecases (2.1 and\or 2.3). I'll test these usecases this weekend.

**Comment by robertoostenveld** [comment]
The container now works with the #44 pull request tha I just merged. So please take a look at the updated `bidsapp.m` and the updates that I did to the `workPackageCerCo` function. 

The main changes to workPackageCerCo are that the path is now set external to the function (to allow for spm12 and the data directories to be located elsewhere), the subject list is pruned such that all subjects have the selected tasks, and the participant/group level is now passed by the bidsapp to the  workPackageCerCo and underlying functions.

**Comment by Marque-CerCo** [comment]
@robertoostenveld 
Sorry for the delay in my reply. I have figured out how bidsapp.m works with use cases 2.1 and 2.3. I am currently reviewing and testing the changes to use case-2.5.

**Comment by Marque-CerCo** [comment]
@robertoostenveld 
I have just finished testing use-case2.5. It works perfectly. However, I have a few comments:
- for the input variable, it works by replacing input with the path to the input directory on my computer,
- for the output variable, it works by replacing output with the path to the output directory on my computer,
- if I copy the command lines in the Readme.md file, it does not work ("input directory does not exist"),
- we can delete the files "firstLevel.m" and "secondLevel.m" because the code does not use them.

**Comment by robertoostenveld** [comment]
I removed the two unused files. 

What do you mean that "it works by replacing input with the path to the input directory"? Do you have to replace it in the code, or can you specify the path on the MATLAB command line as it is supposed to work?

"if I copy the command lines ..., it does not work" -> do you mean the lines for the Linux command line for or the MATLAB command window? Could it be that your input and output directory are not in the `usecase-2.5` directory?

**Comment by Marque-CerCo** [comment]
@robertoostenveld 
When I apply the command line:
matlab -batch "cd wp15/usecase-2.5; restoredefaultpath; addpath spm12 spm12/config spm12/matlabbatch source; bidsapp input output participant" it does not work.
But when I replace input by its path location, it works. For example, when I replace input with "/home/username/input" and output with "/home/username/output," it works. The same idea applies to the other command line.

**Comment by robertoostenveld** [comment]
ok, so there is not really a problem.

**Comment by Marque-CerCo** [comment]
@robertoostenveld 
ok, so the usecase-2.5 works perfectly.
Do we close the discussion ?
