### ISSUE TITLE
use case 2.4 - automated EEG processing using MATLAB

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#5]
[ERPcore](https://osf.io/thsqg/)

The data set includes a small tabular entry characterising human participants and EEG data.

The results to be produced are of the vector and matrices reflecting the different type of types of analyses, based on user requirements. 

The brain data analyses are fully automated, but different outputs are produced based on user requirements—the testing principle of minimisation applied to medical data analysis. 

Relies on matlab/EEGLAB - the dataset includes 40 subjects (24,1GB)

**Comment by marcelzwiers** [comment]
> @arnodelorme I [made the changes](https://github.com/SIESTA-eu/wp15/commit/ee4ef819140e0a24d9e95e75120d16f444ae8699#diff-8dd905ef15147798a93e3edbea03dd584556232f4da78fb401a873658be6ac09) following the page you indicated. 'zapline-plus' is not in the list, but it would be great if you could update the webpage and tell us here what the correct argument is.

Sorry, I don't know which page you are referring to. Anyhow, at some point (I think during the zapline issues) I gave up and handed it all over to you, JM and Cyril

**Comment by robertoostenveld** [comment]
I believe that the plugin installation problems were sufficiently resolved. The analysis pipeline is to be containerized, which means that we'll revisit this anyway. For now I will close this issue.
